### ISSUE TITLE
Bootstrap auf Version 5 updaten

### ISSUE THREAD

**Issue by demianh** [rondo-verlag/song-manager#10]
Man muss leider die meisten Klasse ganz neu machen, aber würde gewisse Dinge vereinfachen.

**Comment by Vento-Nuenenen** [comment]
https://github.com/rondo-verlag/song-manager/pull/18

**Comment by Vento-Nuenenen** [comment]
OK, ich seh s Problem

**Comment by Vento-Nuenenen** [comment]
> Das Layout der "Bearbeiten" Seite ist irgendwie etwas kaputt gegangen und nicht mehr so übersichtlich wie vorher, kannst du das mal anschauen?

Ich hab noch ein Update vom Styling gemacht, sollte jetzt besser sein.
